### ISSUE TITLE
Windows version not working

### ISSUE THREAD

**Issue by CarnageHeart** [freebitcobot/freebitcobot#3]
Windows version still has captcha issues. Also the program will crash after a few attempts with the following information:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Object has been destroyed
    at BrowserWindow.send (C:\Users\CarnageHeart\AppData\Local\Programs\FreeBitcoBot\resources\electron.asar\browser\api\browser-window.js:167:16)
    at C:\Users\CarnageHeart\AppData\Local\Programs\FreeBitcoBot\resources\app.asar\webpack:\src\main\index.js:388:28
    at IncomingMessage.<anonymous> (C:\Users\CarnageHeart\AppData\Local\Programs\FreeBitcoBot\resources\app.asar\node_modules\2captcha\index.js:47:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by ZerooCool** [comment]
I can launch the Windows version, but, and now ?
I have only a new browser open, and, i can see the freebitco.in website, in.
I log in ... and ... nothing.
I need start manually the claim.
